export const SHARP_BOOKS: string[] = [
  "pinnacle",
  "novig",
  "betonline",
  "caesars",
  "betrivers-kambi",
  "draftkings",
  "fanduel",
  "betmgm",
];

export const DFS_BOOKS: string[] = [
  "prizepicks",
  "underdog",
  "underdog-pm",
  "sleeper",
  "boom",
  "dabble",
  "betr",
  "betr-ssb",
  "chalkboard",
  "hotstreak",
  "fliff",
  "rebet",
  "dkpick6",
  "wannaparlay",
];

export const SPORTSBOOK_BOOKS: string[] = [
  "pinnacle",
  "novig",
  "betonline",
  "caesars",
  "betrivers-kambi",
  "draftkings",
  "fanduel",
  "betmgm",
  "fanatics",
  "ballybet",
  "hardrock",
  "betway",
  "thescore",
  "betparx",
  "prophetx",
  "kalshi",
  "polymarket",
];

export const BOOK_ALIASES: Record<string, string> = {
  "prizepicks_best": "prizepicks",
  "prizepicks": "prizepicks",
  "underdog_dfs_best": "underdog",
  "underdog_dfs": "underdog",
  "underdog": "underdog",
  "underdog-pm": "underdog-pm",
  "boomfantasy": "boom",
  "boom": "boom",
  "parlayplay": "parlayplay",
  "chalkboard": "chalkboard",
  "sleeper": "sleeper",
  "dabble_best": "dabble",
  "dabble": "dabble",
  "betr_best": "betr",
  "betr": "betr",
  "betr-ssb": "betr-ssb",
  "pinnacle": "pinnacle",
  "circa": "circa",
  "betfair": "betfair",
  "4cx": "4cx",
  "sporttrade": "sporttrade",
  "novig": "novig",
  "betonline": "betonline",
  "caesars": "caesars",
  "betrivers-kambi": "betrivers-kambi",
  "betrivers": "betrivers-kambi",
  "draftkings": "draftkings",
  "fanduel": "fanduel",
  "betmgm": "betmgm",
  "fanatics": "fanatics",
  "ballybet": "ballybet",
  "hardrock": "hardrock",
  "betway": "betway",
  "thescore": "thescore",
  "betparx": "betparx",
  "prophetx": "prophetx",
  "kalshi": "kalshi",
  "polymarket": "polymarket",
  "dkpick6": "dkpick6",
  "hotstreak": "hotstreak",
  "fliff": "fliff",
  "rebet": "rebet",
  "wannaparlay": "wannaparlay",
};
